# Vagrantfile to mangae multiple Virtual machines
Vagrant.configure("2") do |config|
    # config.vm.provision "shell", inline: "echo Hello"
  
    ##########################################################################
    # centos7 VM
    config.vm.define "vm_centos" do |vm_centos|

      # define operating system to run on vm  
      vm_centos.vm.box = "geerlingguy/centos7"

      # set network configuration

      # private ip
      vm_centos.vm.network "private_network", ip: "192.168.56.20"
      # public bridged network
      vm_centos.vm.network "public_network"

      # set up memory and cpu configuration
      vm_centos.vm.provider "virtualbox" do |cb_c7|
        cb_c7.memory = "1024"
        cb_c7.cpus = 1
      end  

      # run provision command(s)
      vm_centos.vm.provision "shell", inline: <<-SHELL
        whoami
        uptime
        date
      SHELL

    end
    ##########################################################################

    ##########################################################################
    # ubuntu VM
    config.vm.define "vm_ubuntu" do |vm_ubuntu|

        # define operating system to run on vm  
        vm_ubuntu.vm.box = "geerlingguy/ubuntu1804"
  
        # set network configuration
  
        # private ip
        vm_ubuntu.vm.network "private_network", ip: "192.168.56.21"
        # public bridged network
        vm_ubuntu.vm.network "public_network"
  
        # set up memory and cpu configuration
        vm_ubuntu.vm.provider "virtualbox" do |vb_u18|
          vb_u18.memory = "1600"
          vb_u18.cpus = 2
        end  
  
        # run provision command(s)
        vm_ubuntu.vm.provision "shell", inline: <<-SHELL
          whoami
          uptime
          date
        SHELL
  
    end
     ############################################################################

     #############################################################################
    # static website VM
    config.vm.define "vm_static_web" do |vm_static_web|

        # define operating system to run on vm  
        vm_static_web.vm.box = "geerlingguy/centos7"
  
        # set network configuration
  
        # private ip
        vm_static_web.vm.network "private_network", ip: "192.168.56.22"
        # public bridged network
        vm_static_web.vm.network "public_network"
  
        # set up memory and cpu configuration
        vm_static_web.vm.provider "virtualbox" do |vb_st_web|
          vb_st_web.memory = "1024"
          vb_st_web.cpus = 1
        end  

        vm_static_web.vm.provision "shell", inline: <<-SHELL
            # install required packages
            yum install wget httpd unzip -y

            # start and enable httpd server
            systemctl start httpd
            systemctl enable httpd

            # cd into the tmp directory to download static website template
            cd /tmp/

            # download website template
            wget https://www.tooplate.com/zip-templates/2125_artxibition.zip

            # unzip the downloaded zipfile
            unzip -o 2125_artxibition.zip

            # copy the extracted website files to server folder on centos
            cp -r 2125_artxibition/* /var/www/html/

            # restart the server
            systemctl restart httpd

        SHELL
  
    end
    #################################################################################

    ###################################################################################
    # wordpress website VM
    config.vm.define "vm_wordpress_web" do |vm_wordpress_web|

        # define operating system to run on vm  
        vm_wordpress_web.vm.box = "geerlingguy/ubuntu1804"
  
        # set network configuration
  
        # private ip
        vm_wordpress_web.vm.network "private_network", ip: "192.168.56.23"
        # public bridged network
        vm_wordpress_web.vm.network "public_network"
  
        # set up memory and cpu configuration
        vm_wordpress_web.vm.provider "virtualbox" do |vb_wp_wb|
          vb_wp_wb.memory = "1600"
          vb_wp_wb.cpus = 2
        end

        vm_wordpress_web.vm.provision "shell", inline: <<-SHELL
            ######################################################################## 
            # UPDATE AND INSTALL DEPENDENCIES
            sudo apt-get update
            sudo apt install apache2 \
                        ghostscript \
                        libapache2-mod-php \
                        mysql-server \
                        php \
                        php-bcmath \
                        php-curl \
                        php-imagick \
                        php-intl \
                        php-json \
                        php-mbstring \
                        php-mysql \
                        php-xml \
                        php-zip -y
            #########################################################################

            ########################################################################
            # INSTALL WORDPRESS
            # - create wordpress installation file
            sudo mkdir -p /srv/www
            # - create a new user for wordpress server, give user ownership of wordpress server folder (installation folder created above)
            sudo chown www-data: /srv/www
            # - download and extract installation files
            curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www
            #########################################################################

            #########################################################################
            # CONFIGURE APACHE FOR WORDPRESS
            # - create wordpress config file in ubuntu config folder
            touch /etc/apache2/sites-available/wordpress.conf
            # - save wordpress config info in config file
            echo " <VirtualHost *:80>
                    DocumentRoot /srv/www/wordpress
                    <Directory /srv/www/wordpress>
                        Options FollowSymLinks
                        AllowOverride Limit Options FileInfo
                        DirectoryIndex index.php
                        Require all granted
                    </Directory>
                    <Directory /srv/www/wordpress/wp-content>
                        Options FollowSymLinks
                        Require all granted
                    </Directory>
                </VirtualHost> " > /etc/apache2/sites-available/wordpress.conf
            
            # - enable wordpress site, url rewriting, and disable default site
            sudo a2ensite wordpress
            sudo a2enmod rewrite
            sudo a2dissite 000-default

            # - reload apache2 service
            sudo service apache2 reload
            #########################################################################

            #########################################################################
            # CONFIGURE DATABASE
            
            # - create a database for your website
            mysql -u root -e 'CREATE DATABASE wordpress;'
            

            # - create db user and gran permissions for wordpress db
            mysql -u root -e "CREATE USER wordpress@localhost IDENTIFIED BY 'admin1234';"
            mysql -u root -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;"

            # -flush privileges and quit sql shell
            mysql -u root -e "FLUSH PRIVILEGES;"

            # - enable mysql service
            sudo service mysql start
            #########################################################################

            #########################################################################
            # CONFIGURE WORDPRESS TO CONNECT TO DATABASE

            # - copy sample config file created above to a new location (wp-config.php)
            sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php

            # - set db credentials
            sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
            sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
            sudo -u www-data sed -i 's/password_here/admin1234/' /srv/www/wordpress/wp-config.php

            # set secret keys
            sudo -u www-data sed -i 's/AUTH_KEY/ganga/' /srv/www/wordpress/wp-config.php
            sudo -u www-data sed -i 's/SECURE_AUTH_KEY/ganga/' /srv/www/wordpress/wp-config.php
            sudo -u www-data sed -i 's/LOGGED_IN_KEY/ganga/' /srv/www/wordpress/wp-config.php
            sudo -u www-data sed -i 's/NONCE_KEY/ganga/' /srv/www/wordpress/wp-config.php
            sudo -u www-data sed -i 's/AUTH_SALT/ganga/' /srv/www/wordpress/wp-config.php
            sudo -u www-data sed -i 's/SECURE_AUTH_SALT/ganga/' /srv/www/wordpress/wp-config.php
            sudo -u www-data sed -i 's/LOGGED_IN_SALT/ganga/' /srv/www/wordpress/wp-config.php
            sudo -u www-data sed -i 's/NONCE_SALT/ganga/' /srv/www/wordpress/wp-config.php
            ##################################################################################

            sudo systemctl reload apache2
            
        SHELL
  
    end
    ###############################################################################################################################
  end